apiVersion: v1
kind: ConfigMap
metadata:
  name: db-facade
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Neo4j</title>
        <meta http-equiv="refresh" content="0; url=https://testing.db.more-cars.internal:30473" />
      </head>
      <body>
        <p>Redirecting to Neo4j Browserâ€¦</p>
      </body>
    </html>
