apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-db-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://prod.db.more-cars.internal:30473
spec:
  tls:
    - hosts:
        - prod.db.more-cars.internal
      secretName: certificate-db
  rules:
    - host: prod.db.more-cars.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder
                port:
                  number: 80
