apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  tls:
    - hosts:
        - testing.api.more-cars.internal
      secretName: certificate-api
    - hosts:
        - testing.swagger.more-cars.internal
      secretName: certificate-api
  rules:
    - host: testing.api.more-cars.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
    - host: testing.swagger.more-cars.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openapi-spec-service
                port:
                  number: 80
