apiVersion: v1
kind: Service
metadata:
  name: openapi-spec-service
spec:
  type: ClusterIP
  selector:
    app: openapi-spec
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
