apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openapi-spec
spec:
  parentRefs:
    - name: more-cars-gateway
      sectionName: more-cars

  hostnames:
    - default.swagger.more-cars.internal

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: openapi-spec-service
          port: 80
