apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openapi-spec-http
spec:
  parentRefs:
    - name: more-cars-gateway
      sectionName: more-cars-http

  hostnames:
    - swagger.default.more-cars.internal

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
