apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../app
  - namespace.yaml

namespace: testing

patches:
  - target:
      kind: Service
      name: api-db-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31473
      - op: replace
        path: /spec/ports/1/nodePort
        value: 31474
      - op: replace
        path: /spec/ports/2/nodePort
        value: 31687
