name: Acceptance Stage

on:
  workflow_call:

jobs:
  run-smoke-tests:
    uses: ./.github/workflows/run-smoke-tests.yml
    with:
      environment: testing
      version: ${{ github.sha }}
    secrets: inherit
  run-developer-tests:
    uses: ./.github/workflows/run-developer-tests.yml
    with:
      environment: testing
      version: ${{ github.sha }}
    secrets: inherit