name: Run Developer Tests

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: testing
      version:
        type: string
        default: latest
      code_coverage:
        type: boolean
        default: false
      reports_path:
        type: string
        default: ./test-reports/developer

jobs:
  run-developer-tests:
    name: Run Developer Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Node.js dependencies
        run: npm ci

      - name: Authorizing GitHub to access the Google Cloud account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Create Developer Tests Job in GKE
        run: npm run tests:developer
        env:
          TEST_RUNNER: gke
          TARGET_CLUSTER: gke
          TARGET_ENVIRONMENT: ${{ inputs.environment }}
          TEST_VERSION: ${{ inputs.version }}
          CODE_COVERAGE_ENABLED: ${{ inputs.code_coverage }}
          REPORTS_PATH: ${{ inputs.reports_path }}
